"""empty message

Revision ID: 740c46c95f9d
Revises: b95001e0b5ec
Create Date: 2019-04-23 18:50:37.148263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740c46c95f9d'
down_revision = 'b95001e0b5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('user_id', sa.Integer()))
    #op.create_foreign_key(None, 'event', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'user_id')
    # ### end Alembic commands ###
